### ISSUE TITLE
Fetch Failed for Japan Exclusive Stickers

### ISSUE THREAD

**Issue by NateTheL0ser** [jeffshee/LINEStickerKeyboard#10]
I tried fetching both manually and automatically this sticker set: https://store.line.me/stickershop/product/13499032
But it failed every time...

**Comment by NateTheL0ser** [comment]
I had to use a VPN for it which I guess is a workaround. I'm not sure if that's a solution enough for it though...

**Comment by jeffshee** [comment]
@NateTheL0ser Hi. Thanks for reporting. Yes, you will need a VPN for Japan exclusive stickers, if you are not living in Japan. Unfortunately it is the limitation. Luckily there is many free VPN that offer Japan server, so it might not be too difficult to get those exclusive stickers. 😊
