### ISSUE TITLE
who to

### ISSUE THREAD

**Issue by dangerchitthu** [jeffshee/LINEStickerKeyboard#3]
my hosting to use 
html code smaple 
pls

**Comment by jeffshee** [comment]
Hmm, I'm afraid that I couldn't understand what you mean. Please describe it more clearly, thanks.

I'm going to close this ticket. If you have problem regarding "LINEStickerKeyboard" (bugs etc.), feel free to open another ticket. Please keep Issues clean and organized!

**Comment by dangerchitthu** [comment]
Sticker Download 
Smaple (mtml) file smaple code

**Comment by jeffshee** [comment]
This keyboard is for Android, only Android.
And I guess you ask for code sample for web(JavaScript)? What are you trying to achieve? Did you tried doing it? 

Also make sure you write in proper English, at least comprehensible (+_+)
