### ISSUE TITLE
Some sticker sets not downloading correctly

### ISSUE THREAD

**Issue by Ironkeroro** [jeffshee/LINEStickerKeyboard#9]
All stickers in the set download as empty files (not blank but rather an image file without an image). Funnily enough all anime related. Some region locked some not. 

what I've tried that failed. 569; 595; 564; 2462; 683

working ones: 2999; 3000; 3001; 2998; 2746; 2822; 2710; 925; 1917

they don't seem to follow the odd counting by 2's as the other issue. at first i thought it might be to do with how small the id's were but, 925 worked and 2462 failed.

**Comment by jeffshee** [comment]
Thanks for reporting, LINE store changes the scheme of the stickers' URL sometimes, and if that happens, I have to change some codes to cope with those changes.
From what I found so far, the issue seems to be:
This link will work
```https://stickershop.line-scdn.net/stickershop/v1/sticker/4153/android/sticker.png```
But this link wouldn't (I used this scheme in my code)
```https://stickershop.line-scdn.net/stickershop/v1/sticker/4153/IOS/sticker@2x.png```
